"""Create a relationship and readers table 

Revision ID: 815f1b664711
Revises: 
Create Date: 2021-11-15 19:27:06.055486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815f1b664711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'readers', ['reader_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'reader_pk')
    # ### end Alembic commands ###
